version: "2"

services:
  bot_alpha_checker:
#    image: ferdinandthe2/bot_alpha_checker:latest
    build:
      dockerfile: Dockerfile
      # Launch container only after 'postgres_alpha_checker'
      # returns positive healthcheck result
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      APP_USER: ${APP_USER}
      PASSWORD: ${PASSWORD}

      HOST_LINK: ${HOST_LINK}
      PORT_LINK: ${PORT_LINK}
      DB_NAME_LINK: ${DB_NAME_LINK}
      APP_USER_LINK: ${APP_USER_LINK}
      PASSWORD_LINK: ${PASSWORD_LINK}

      HOST_POSTBACK: ${HOST_POSTBACK}
      PORT_POSTBACK: ${PORT_POSTBACK}
      DB_NAME_POSTBACK: ${DB_NAME_POSTBACK}
      APP_USER_POSTBACK: ${APP_USER_POSTBACK}
      PASSWORD_POSTBACK: ${PASSWORD_POSTBACK}

    volumes:
      - checker_logs:/alpha_checker/logs

  django_alpha_checker:
#    image: ferdinandthe2/django_alpha_checker:latest
    build: ./django_alpha_checker
    # Launch container only after 'postgres_alpha_checker'
    # returns positive healthcheck result
    entrypoint: /django_alpha_checker/entrypoint.sh
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      APP_USER: ${APP_USER}
      PASSWORD: ${PASSWORD}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_PASSWORD}
    ports:
      - "8080:8000"

volumes:
  checker_logs: