# Generated by Django 4.2.6 on 2023-10-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='stats.checkeruser')),
            ],
            options={
                'db_table': 'inspector"."update_inspector',
            },
        ),
        migrations.CreateModel(
            name='GetInfoInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='stats.checkeruser')),
            ],
            options={
                'db_table': 'inspector"."get_info_inspector',
            },
        ),
        migrations.CreateModel(
            name='FoundClientByInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='stats.checkeruser')),
            ],
            options={
                'db_table': 'inspector"."found_client_by_inspector',
            },
        ),
    ]
